"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
trunk-ignore(buf-lint/PACKAGE_DIRECTORY_MATCH)"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _Team:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _TeamEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Team.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    Unspecifed_Color: _Team.ValueType  # 0
    """
    Unspecifed
    """
    White: _Team.ValueType  # 1
    """
    White
    """
    Yellow: _Team.ValueType  # 2
    """
    Yellow
    """
    Orange: _Team.ValueType  # 3
    """
    Orange
    """
    Magenta: _Team.ValueType  # 4
    """
    Magenta
    """
    Red: _Team.ValueType  # 5
    """
    Red
    """
    Maroon: _Team.ValueType  # 6
    """
    Maroon
    """
    Purple: _Team.ValueType  # 7
    """
    Purple
    """
    Dark_Blue: _Team.ValueType  # 8
    """
    Dark Blue
    """
    Blue: _Team.ValueType  # 9
    """
    Blue
    """
    Cyan: _Team.ValueType  # 10
    """
    Cyan
    """
    Teal: _Team.ValueType  # 11
    """
    Teal
    """
    Green: _Team.ValueType  # 12
    """
    Green
    """
    Dark_Green: _Team.ValueType  # 13
    """
    Dark Green
    """
    Brown: _Team.ValueType  # 14
    """
    Brown
    """

class Team(_Team, metaclass=_TeamEnumTypeWrapper): ...

Unspecifed_Color: Team.ValueType  # 0
"""
Unspecifed
"""
White: Team.ValueType  # 1
"""
White
"""
Yellow: Team.ValueType  # 2
"""
Yellow
"""
Orange: Team.ValueType  # 3
"""
Orange
"""
Magenta: Team.ValueType  # 4
"""
Magenta
"""
Red: Team.ValueType  # 5
"""
Red
"""
Maroon: Team.ValueType  # 6
"""
Maroon
"""
Purple: Team.ValueType  # 7
"""
Purple
"""
Dark_Blue: Team.ValueType  # 8
"""
Dark Blue
"""
Blue: Team.ValueType  # 9
"""
Blue
"""
Cyan: Team.ValueType  # 10
"""
Cyan
"""
Teal: Team.ValueType  # 11
"""
Teal
"""
Green: Team.ValueType  # 12
"""
Green
"""
Dark_Green: Team.ValueType  # 13
"""
Dark Green
"""
Brown: Team.ValueType  # 14
"""
Brown
"""
Global___Team: _TypeAlias = Team  # noqa: Y015

class _MemberRole:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _MemberRoleEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_MemberRole.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    Unspecifed: _MemberRole.ValueType  # 0
    """
    Unspecifed
    """
    TeamMember: _MemberRole.ValueType  # 1
    """
    Team Member
    """
    TeamLead: _MemberRole.ValueType  # 2
    """
    Team Lead
    """
    HQ: _MemberRole.ValueType  # 3
    """
    Headquarters
    """
    Sniper: _MemberRole.ValueType  # 4
    """
    Airsoft enthusiast
    """
    Medic: _MemberRole.ValueType  # 5
    """
    Medic
    """
    ForwardObserver: _MemberRole.ValueType  # 6
    """
    ForwardObserver
    """
    RTO: _MemberRole.ValueType  # 7
    """
    Radio Telephone Operator
    """
    K9: _MemberRole.ValueType  # 8
    """
    Doggo
    """

class MemberRole(_MemberRole, metaclass=_MemberRoleEnumTypeWrapper):
    """
    Role of the group member
    """

Unspecifed: MemberRole.ValueType  # 0
"""
Unspecifed
"""
TeamMember: MemberRole.ValueType  # 1
"""
Team Member
"""
TeamLead: MemberRole.ValueType  # 2
"""
Team Lead
"""
HQ: MemberRole.ValueType  # 3
"""
Headquarters
"""
Sniper: MemberRole.ValueType  # 4
"""
Airsoft enthusiast
"""
Medic: MemberRole.ValueType  # 5
"""
Medic
"""
ForwardObserver: MemberRole.ValueType  # 6
"""
ForwardObserver
"""
RTO: MemberRole.ValueType  # 7
"""
Radio Telephone Operator
"""
K9: MemberRole.ValueType  # 8
"""
Doggo
"""
Global___MemberRole: _TypeAlias = MemberRole  # noqa: Y015

@_typing.final
class TAKPacket(_message.Message):
    """
    Packets for the official ATAK Plugin
    """

    DESCRIPTOR: _descriptor.Descriptor

    IS_COMPRESSED_FIELD_NUMBER: _builtins.int
    CONTACT_FIELD_NUMBER: _builtins.int
    GROUP_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    PLI_FIELD_NUMBER: _builtins.int
    CHAT_FIELD_NUMBER: _builtins.int
    DETAIL_FIELD_NUMBER: _builtins.int
    is_compressed: _builtins.bool
    """
    Are the payloads strings compressed for LoRA transport?
    """
    detail: _builtins.bytes
    """
    Generic CoT detail XML
    May be compressed / truncated by the sender (EUD)
    """
    @_builtins.property
    def contact(self) -> Global___Contact:
        """
        The contact / callsign for ATAK user
        """

    @_builtins.property
    def group(self) -> Global___Group:
        """
        The group for ATAK user
        """

    @_builtins.property
    def status(self) -> Global___Status:
        """
        The status of the ATAK EUD
        """

    @_builtins.property
    def pli(self) -> Global___PLI:
        """
        TAK position report
        """

    @_builtins.property
    def chat(self) -> Global___GeoChat:
        """
        ATAK GeoChat message
        """

    def __init__(
        self,
        *,
        is_compressed: _builtins.bool = ...,
        contact: Global___Contact | None = ...,
        group: Global___Group | None = ...,
        status: Global___Status | None = ...,
        pli: Global___PLI | None = ...,
        chat: Global___GeoChat | None = ...,
        detail: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["chat", b"chat", "contact", b"contact", "detail", b"detail", "group", b"group", "payload_variant", b"payload_variant", "pli", b"pli", "status", b"status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chat", b"chat", "contact", b"contact", "detail", b"detail", "group", b"group", "is_compressed", b"is_compressed", "payload_variant", b"payload_variant", "pli", b"pli", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload_variant: _TypeAlias = _typing.Literal["pli", "chat", "detail"]  # noqa: Y015
    _WhichOneofArgType_payload_variant: _TypeAlias = _typing.Literal["payload_variant", b"payload_variant"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload_variant) -> _WhichOneofReturnType_payload_variant | None: ...

Global___TAKPacket: _TypeAlias = TAKPacket  # noqa: Y015

@_typing.final
class GeoChat(_message.Message):
    """
    ATAK GeoChat message
    """

    DESCRIPTOR: _descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: _builtins.int
    TO_FIELD_NUMBER: _builtins.int
    TO_CALLSIGN_FIELD_NUMBER: _builtins.int
    message: _builtins.str
    """
    The text message
    """
    to: _builtins.str
    """
    Uid recipient of the message
    """
    to_callsign: _builtins.str
    """
    Callsign of the recipient for the message
    """
    def __init__(
        self,
        *,
        message: _builtins.str = ...,
        to: _builtins.str | None = ...,
        to_callsign: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_to", b"_to", "_to_callsign", b"_to_callsign", "to", b"to", "to_callsign", b"to_callsign"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_to", b"_to", "_to_callsign", b"_to_callsign", "message", b"message", "to", b"to", "to_callsign", b"to_callsign"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__to: _TypeAlias = _typing.Literal["to"]  # noqa: Y015
    _WhichOneofArgType__to: _TypeAlias = _typing.Literal["_to", b"_to"]  # noqa: Y015
    _WhichOneofReturnType__to_callsign: _TypeAlias = _typing.Literal["to_callsign"]  # noqa: Y015
    _WhichOneofArgType__to_callsign: _TypeAlias = _typing.Literal["_to_callsign", b"_to_callsign"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__to) -> _WhichOneofReturnType__to | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__to_callsign) -> _WhichOneofReturnType__to_callsign | None: ...

Global___GeoChat: _TypeAlias = GeoChat  # noqa: Y015

@_typing.final
class Group(_message.Message):
    """
    ATAK Group
    <__group role='Team Member' name='Cyan'/>
    """

    DESCRIPTOR: _descriptor.Descriptor

    ROLE_FIELD_NUMBER: _builtins.int
    TEAM_FIELD_NUMBER: _builtins.int
    role: Global___MemberRole.ValueType
    """
    Role of the group member
    """
    team: Global___Team.ValueType
    """
    Team (color)
    Default Cyan
    """
    def __init__(
        self,
        *,
        role: Global___MemberRole.ValueType = ...,
        team: Global___Team.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["role", b"role", "team", b"team"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Group: _TypeAlias = Group  # noqa: Y015

@_typing.final
class Status(_message.Message):
    """
    ATAK EUD Status
    <status battery='100' />
    """

    DESCRIPTOR: _descriptor.Descriptor

    BATTERY_FIELD_NUMBER: _builtins.int
    battery: _builtins.int
    """
    Battery level
    """
    def __init__(
        self,
        *,
        battery: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["battery", b"battery"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Status: _TypeAlias = Status  # noqa: Y015

@_typing.final
class Contact(_message.Message):
    """
    ATAK Contact
    <contact endpoint='0.0.0.0:4242:tcp' phone='+12345678' callsign='FALKE'/>
    """

    DESCRIPTOR: _descriptor.Descriptor

    CALLSIGN_FIELD_NUMBER: _builtins.int
    DEVICE_CALLSIGN_FIELD_NUMBER: _builtins.int
    callsign: _builtins.str
    """
    Callsign
    """
    device_callsign: _builtins.str
    """
    Device callsign

    IP address of endpoint in integer form (0.0.0.0 default)
    """
    def __init__(
        self,
        *,
        callsign: _builtins.str = ...,
        device_callsign: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["callsign", b"callsign", "device_callsign", b"device_callsign"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Contact: _TypeAlias = Contact  # noqa: Y015

@_typing.final
class PLI(_message.Message):
    """
    Position Location Information from ATAK
    """

    DESCRIPTOR: _descriptor.Descriptor

    LATITUDE_I_FIELD_NUMBER: _builtins.int
    LONGITUDE_I_FIELD_NUMBER: _builtins.int
    ALTITUDE_FIELD_NUMBER: _builtins.int
    SPEED_FIELD_NUMBER: _builtins.int
    COURSE_FIELD_NUMBER: _builtins.int
    latitude_i: _builtins.int
    """
    The new preferred location encoding, multiply by 1e-7 to get degrees
    in floating point
    """
    longitude_i: _builtins.int
    """
    The new preferred location encoding, multiply by 1e-7 to get degrees
    in floating point
    """
    altitude: _builtins.int
    """
    Altitude (ATAK prefers HAE)
    """
    speed: _builtins.int
    """
    Speed
    """
    course: _builtins.int
    """
    Course in degrees
    """
    def __init__(
        self,
        *,
        latitude_i: _builtins.int = ...,
        longitude_i: _builtins.int = ...,
        altitude: _builtins.int = ...,
        speed: _builtins.int = ...,
        course: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["altitude", b"altitude", "course", b"course", "latitude_i", b"latitude_i", "longitude_i", b"longitude_i", "speed", b"speed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PLI: _TypeAlias = PLI  # noqa: Y015
