# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: meshtastic/protobuf/leo.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'meshtastic/protobuf/leo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dmeshtastic/protobuf/leo.proto\x12\x13meshtastic.protobuf\"\xa8\x02\n\x03TLE\x12\t\n\x01N\x18\x01 \x01(\r\x12\n\n\x02YE\x18\x02 \x01(\r\x12\n\n\x02TE\x18\x03 \x01(\x02\x12\n\n\x02IN\x18\x04 \x01(\x02\x12\n\n\x02RA\x18\x05 \x01(\x02\x12\n\n\x02\x45\x43\x18\x06 \x01(\x02\x12\n\n\x02WP\x18\x07 \x01(\x02\x12\n\n\x02MA\x18\x08 \x01(\x02\x12\n\n\x02MM\x18\t \x01(\x02\x12\n\n\x02M2\x18\n \x01(\x02\x12\n\n\x02RV\x18\x0b \x01(\r\x12\n\n\x02\x45S\x18\x0c \x01(\r\x12\x19\n\x0csat_fullname\x18\r \x01(\tH\x00\x88\x01\x01\x12\x1d\n\x10\x63onstellation_id\x18\x0e \x01(\rH\x01\x88\x01\x01\x12\x1d\n\x10last_update_time\x18\x0f \x01(\rH\x02\x88\x01\x01\x42\x0f\n\r_sat_fullnameB\x13\n\x11_constellation_idB\x13\n\x11_last_update_time\"\xdd\x02\n\tLEOConfig\x12\x42\n\naddreplace\x18\x01 \x01(\x0b\x32,.meshtastic.protobuf.LEOConfig.TLEAddReplaceH\x00\x12:\n\x06remove\x18\x02 \x01(\x0b\x32(.meshtastic.protobuf.LEOConfig.TLERemoveH\x00\x12\x16\n\tsignature\x18\x03 \x01(\x0cH\x01\x88\x01\x01\x1a\x87\x01\n\rTLEAddReplace\x12\x0f\n\x07is_test\x18\x01 \x01(\x08\x12%\n\x03tle\x18\x02 \x01(\x0b\x32\x18.meshtastic.protobuf.TLE\x12\x15\n\x08\x61perture\x18\x03 \x01(\rH\x00\x88\x01\x01\x12\x11\n\x04gain\x18\x04 \x01(\x02H\x01\x88\x01\x01\x42\x0b\n\t_apertureB\x07\n\x05_gain\x1a\x16\n\tTLERemove\x12\t\n\x01N\x18\x01 \x01(\rB\x08\n\x06\x61\x63tionB\x0c\n\n_signatureB^\n\x13\x63om.geeksville.meshB\tLEOProtosZ\"github.com/meshtastic/go/generated\xaa\x02\x14Meshtastic.Protobufs\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meshtastic.protobuf.leo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.geeksville.meshB\tLEOProtosZ\"github.com/meshtastic/go/generated\252\002\024Meshtastic.Protobufs\272\002\000'
  _globals['_TLE']._serialized_start=55
  _globals['_TLE']._serialized_end=351
  _globals['_LEOCONFIG']._serialized_start=354
  _globals['_LEOCONFIG']._serialized_end=703
  _globals['_LEOCONFIG_TLEADDREPLACE']._serialized_start=520
  _globals['_LEOCONFIG_TLEADDREPLACE']._serialized_end=655
  _globals['_LEOCONFIG_TLEREMOVE']._serialized_start=657
  _globals['_LEOCONFIG_TLEREMOVE']._serialized_end=679
# @@protoc_insertion_point(module_scope)
